# Generated by Django 2.2 on 2019-10-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191025_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='noimage.png', null=True, upload_to=''),
        ),
    ]
