# Generated by Django 2.2 on 2019-10-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191025_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='noimage.png', upload_to=''),
        ),
    ]
