# Generated by Django 2.2 on 2019-11-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191101_0430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
