# Generated by Django 2.2 on 2019-12-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event',
        ),
    ]
